# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p:\API\ahmed\ui\Facebook\Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1095, 740)
        Form.setToolTipDuration(-1)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMinimumSize(QtCore.QSize(0, 400))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3, 0, QtCore.Qt.AlignHCenter)
        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_Select = QtWidgets.QWidget(self.widget_2)
        self.widget_Select.setObjectName("widget_Select")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_Select)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Select_Account = QtWidgets.QPushButton(self.widget_Select)
        self.Select_Account.setObjectName("Select_Account")
        self.horizontalLayout_4.addWidget(self.Select_Account, 0, QtCore.Qt.AlignLeft)
        self.widget_5 = QtWidgets.QWidget(self.widget_Select)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Accounts = QtWidgets.QLabel(self.widget_5)
        self.Accounts.setObjectName("Accounts")
        self.horizontalLayout_3.addWidget(self.Accounts)
        self.Number_Account = QtWidgets.QLabel(self.widget_5)
        self.Number_Account.setObjectName("Number_Account")
        self.horizontalLayout_3.addWidget(self.Number_Account)
        self.horizontalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_16.addWidget(self.widget_Select)
        self.Start = QtWidgets.QPushButton(self.widget_2)
        self.Start.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.Start.setCheckable(True)
        self.Start.setObjectName("Start")
        self.verticalLayout_16.addWidget(self.Start, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_Info = QtWidgets.QWidget(self.widget_4)
        self.widget_Info.setObjectName("widget_Info")
        self.verticalLayout.addWidget(self.widget_Info)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Test"))
        self.Select_Account.setText(_translate("Form", "Select Account"))
        self.Accounts.setText(_translate("Form", "Accounts :"))
        self.Number_Account.setText(_translate("Form", "0"))
        self.Start.setText(_translate("Form", "Start"))
